### ISSUE TITLE
Can not display Chinese characters

### ISSUE THREAD

**Issue by tofarfar** [chearon/dropflow#15]
Hi, this project is very useful for me. But it seems can't display chinese character.

I download a chinese font from google font [here](https://fonts.google.com/noto/specimen/Noto+Sans+SC?subset=chinese-simplified&noto.script=Hans). Copy your example code, just replace the font to the downloaded font, and replace the 'hello world' to ramdom chinese character. The result is two square. It works if i change back to english.

![out](https://github.com/chearon/dropflow/assets/6022398/c9798f59-26c9-402c-aa74-a2dcfd36083f)

Thanks for your great work!

**Comment by tofarfar** [comment]
I know why.

I didn't use the `node-canvas` package, instead  i used `@napi-rs/canvas` because it works out of box. In this case, I need to register font using @napi-rs/canvas's`GlobalFonts.registerFromPath` instead of `flow.registerFont`. This solve my problem.

**Comment by chearon** [comment]
Glad you figured it out. I'll look into adding something to the README for `@napi-rs/canvas`.
