### ISSUE TITLE
The combination emoji(👩‍❤️‍👩) is not displayed correctly

### ISSUE THREAD

**Issue by Jocs** [chearon/dropflow#19]
When entering some combination emojis like(👩‍❤️‍👩), it is not displayed correctly.

and it is expected to be displayed as follows:
<img width="654" alt="截屏2024-04-27 01 00 17" src="https://github.com/chearon/dropflow/assets/9712830/c72f1b6d-4382-41dd-97e2-03c57fea911d">

but it displayed like this:
<img width="659" alt="截屏2024-04-27 01 00 42" src="https://github.com/chearon/dropflow/assets/9712830/7ee16185-93bb-4759-af08-958002f955cd">

**Comment by chearon** [comment]
I can reproduce that in Safari, but Firefox and Chrome produce this:

<img width="67" alt="Screen Shot 2024-04-28 at 2 20 10 PM" src="https://github.com/chearon/dropflow/assets/78187/1e43f9e5-8c0a-4352-a907-af74e5124a3b">

I'll post the rest of my response on your PR.
