### ISSUE TITLE
Italic rendering as bold

### ISSUE THREAD

**Issue by jfrueh** [chearon/dropflow#21]
This is a really cool project - thanks for your work on it. 

I'm running into an issue where font-style: italic get's a bold style applied to it when there is a bold tag before it.

Here's a code example:

 var textflow = `
    <span style="font-size:30px;font-family:'Noto Sans';font-weight:normal;">
      <span>normal</span>
      <br />
      <span style="font-weight:bold">bold</span>
      <br />
      <span style="font-style:italic">italic</span>
    </span>`;

  var canvas = document.createElement('canvas');
  canvas.style.width = 500;
  canvas.style.height = 500;
  canvas.style.position = 'absolute';
  canvas.style.top = '100px';
  canvas.style.left = '100px';
  document.body.appendChild(canvas);

  await flow.loadNotoFonts(flow.parse(textflow));
  var rootElement = flow.parse(textflow);
  var tree = flow.generate(rootElement);
  flow.layout(tree, 500, 500);
  flow.paintToCanvas(tree, canvas.getContext("2d"));

The result of the paintToCanvas is a canvas that renders like this:
<img width="83" alt="image" src="https://github.com/chearon/dropflow/assets/1854052/db14ad79-20ad-4805-b508-48030838ed8b">

The word 'italic' should not be in bold.  Any ideas on what could be causing this or if there is something I'm doing wrong?

Thanks,

**Comment by chearon** [comment]
I see that same problem in the demo website. The Noto Sans 400/Italic font has its weight set to 1 (instead of 400) for some reason, so it's not getting selected. I'll have it fixed when I get back from vacation. Thanks for reporting!

**Comment by chearon** [comment]
It was more complicated than the font having the wrong value in it; I think it was a bug in HarfBuzz, but I also needed to upgrade emscripten to get it to work with compiler optimizations enabled.

Anyways, it works now. I've got a couple of simple properties to add and then I'll release. Thanks again for the bug reports.
