### ISSUE TITLE
Line height inconsistencies

### ISSUE THREAD

**Issue by jfrueh** [chearon/dropflow#23]
I've been battling some line height issues (or at least what I believe are issues related to line height on block style elements).   The image below is just really simple HTML on the left and that same HTML rendered to the canvas on the right.  My expectation was that both words would have the same vertical position.

Code for the left 'Test':
` <p style="font-size:120px;font-family:'Noto Sans'">Test</p>`

Code for the right 'Test':
```
var textflow = `<p style="font-size:120px;font-family:'Noto Sans'">Test</p>`;
var rootElement = flow.parse(textflow);
var tree = flow.generate(rootElement);
flow.paintToCanvas(tree, context)
```

Wondering if there is something obvious that I'm missing here?  I've tried every combination of line-height and margins that I can think of. Any ideas what I might be overlooking (or if there is an issue)?  

<img width="740" alt="image" src="https://github.com/chearon/dropflow/assets/1854052/c5971be1-8584-423a-bac4-71efe692f5c4">

**Comment by chearon** [comment]
I think that's the margin actually. Do the differences go away with `margin: 0`? I missed this duality in the spec:

> The 'em' unit is equal to the computed value of the ['font-size'](https://www.w3.org/Style/css2-updates/css2/fonts.html#propdef-font-size) property of the element on which it is used. The exception is when 'em' occurs in the value of the 'font-size' property itself, in which case it refers to the font size of the parent element.

— [§ 4.3.2 Lengths](https://www.w3.org/Style/css2-updates/css2/syndata.html#value-def-length)

Working on a fix... thanks for the bug report!

**Comment by jfrueh** [comment]
Awesome, works great.  Thank you!
